export const IMAGES_LOAD_REQUEST = 'IMAGES_LOAD_REQUEST';
export const IMAGES_LOAD_SUCCESS = 'IMAGES_LOAD_SUCCESS';
export const IMAGES_LOAD_ERROR = 'IMAGES_LOAD_ERROR';
export const SEARCH_QUERY_CHANGE = 'SEARCH_QUERY_CHANGE';
export const IMAGES_CLEAR = 'IMAGES_CLEAR';